### ISSUE TITLE
HAPPE 3.0 vague wavelet thresholding error

### ISSUE THREAD

**Issue by wecarsoniv** [PINE-Lab/HAPPE#1]
My lab is trying to use HAPPE 3.0 to process EEG data exported from Net Station stored in .mat file format.

For each file I've tried to run, I get the following error part way through processing: "ERROR: Wavelet thresholding failed." No additional error message is displayed that could tell me more specifically what is going wrong. After the HAPPE 3.0 finishes running, there are no output files in any of the HAPPE-created folders 2 through 5. There are only files in the first folder, "1 - intermediate_processing".

I am using the HAPPE 3.0 version from this GitHub repo as of 9/29/2022. What is causing this error message, specifically? How do I resolve this? Any help is appreciated, thanks.

**Comment by PINE-Lab** [comment]
Hi, we've provided a webpage for troubleshooting here: https://www.plasticityinneurodevelopmentlab.com/troubleshooting

**Comment by jibrjabr** [comment]
Also having this error. Wavelet toolbox is installed. 

Matlab 2020b
Happe v3 installed today (07/12/2022)

[inputParameters_07-12-2022.mat.zip](https://github.com/PINE-Lab/HAPPE/files/10181121/inputParameters_07-12-2022.mat.zip)

[6 - quality_assessment_outputs.zip](https://github.com/PINE-Lab/HAPPE/files/10181124/6.-.quality_assessment_outputs.zip)

**Comment by jibrjabr** [comment]
> Also having this error. Wavelet toolbox is installed.
> 
> Matlab 2020b Happe v3 installed today (07/12/2022)
> 
> [inputParameters_07-12-2022.mat.zip](https://github.com/PINE-Lab/HAPPE/files/10181121/inputParameters_07-12-2022.mat.zip)
> 
> [6 - quality_assessment_outputs.zip](https://github.com/PINE-Lab/HAPPE/files/10181124/6.-.quality_assessment_outputs.zip)

Update: it ran OK on a different machine with Matlab 2021b.
