### ISSUE TITLE
failed error log save

### ISSUE THREAD

**Issue by neil-gallagher** [PINE-Lab/HAPPE#2]
When running HAPPE on my data, it crashes with the following final few lines of output:
```
Saving error log...
Error using cell2table (line 77)
The VariableNames property must contain one name for each variable in the table.
Error in HAPPE_v3 (line 1116)
    writetable(cell2table(errorLog, 'VariableNames', {'File', ... 
```
This was solved by changing line 1099 to:
```
    errorLog = [errorLog; {'Outputs', ME.message, ''}] ;
```

**Comment by PINE-Lab** [comment]
Hi, could you please confirm which script version you are running because those line numbers don't match the current code? Thanks!

**Comment by neil-gallagher** [comment]
I’m not really sure where to find the version for your repository, but I believe this is from commit 928b5ce4f3 on Sep 6.

From: PINE_Lab ***@***.***>
Date: Monday, October 3, 2022 at 10:59 AM
To: PINE-Lab/HAPPE ***@***.***>
Cc: Neil Gallagher ***@***.***>, Author ***@***.***>
Subject: Re: [PINE-Lab/HAPPE] failed error log save (Issue #2)

Hi, could you please confirm which script version you are running because those line numbers don't match the current code? Thanks!

**Comment by PINE-Lab** [comment]
The most recent commit is version 6bf52a5 from September 23. It's possible that whatever was causing this error has already been addressed. Could you please download the most recent version and confirm?

**Comment by PINE-Lab** [comment]
We've located the source of the issue and have hopefully addressed it with a bug fix!
