### ISSUE TITLE
ECGone NOT currently functional!

### ISSUE THREAD

**Issue by PINE-Lab** [PINE-Lab/HAPPE#3]
If you try to use the ECGone option, HAPPE will not run. This feature is not yet functional! This should be resolved as we release the feature in a later HAPPE update.

**Comment by xplsek03** [comment]
Still doesn't work on HAPPE_v4 though, errlog says:

`data.set,Index in position 2 exceeds array bounds. Index must not exceed 30000.,Line 93 in Ĭ; Line 115 in ʢ; Line 102 in irfilt; Line 112 in op_eegfiltnew; Line 104 in appe_wavThresh; Line 72 in APPE_v4; Line 112 in run`

This error seems to be coming from wavelet thresholding, according to fact that ECGone is right before it, I presume there is malformatted output coming out. I will try to look at it, but not a matlab programmer..
