### ISSUE TITLE
Error: readlocs()

### ISSUE THREAD

**Issue by sarahechang123** [PINE-Lab/HAPPE#4]
Hi! 

Thank you for providing this amazing free resource! I'm trying to use HAPPE on the tutorial dataset (Visual-Evoked Potential (VEP) Event-Related Files) and will hopefully use the tool for a similar task EEG data collected in my lab.

I'm running HAPPE v3 (downloaded 01/29/23) on a PC (MATLAB R2022b). My input parameters are the following:
Density: High (> 30 channels)
Resting State or Task: Task
 - Task Onset Tags: vep+
    - Conditions: NA
 - ERP Analysis: Yes
Data File Format: .raw (Netstation simple binary)
Acquisition Layout: 128 channel EGI HydroCel Geodesic Sensor Net
Channels: FP1, FP2, F7, F3, F4, F8, C3, C4, T5, PZ, T6, O1, O2, T3, T4, P3, P4, Fz, CZ, E71, E75, E76, E6, E86, E53, E110, E35, E40, E23, E3, E109, E13, E112, E46, E102, E16, E28, E117, E67, E77, E31, E80
Line Noise Frequency: 60 Hz
Line Noise Reduction Method: CleanLine - Default
Resample: Off
Filter:  - Lowpass Cutoff: 35
 - Highpass Cutoff: 0.3
 - Type: EEGLAB's FIR
Bad Channel Detection: On
 - Bad Channel Detection Method: Default
Wavelet Thresholding: Default
 - Threshold Rule: Soft
MuscIL: Off
Segmentation: On
 - Starting Parameter for Stimulus: -0.1 seconds
 - Ending Parameter for Stimulus: 0.45 seconds
 - Task Offset: 19 milliseconds
 - Baseline Correction: On
    - Baseline Correction Start: -100 milliseconds
    - Baseline Correction End: 0 milliseconds
Interpolation: Off
Segment Rejection: On
 - Segment Rejection Method: Both amplitude and similarity criteria
    - Minimum Segment Rejection Threshold: -200
    - Maximum Segment Rejection Threshold: 200
    - Segment Rejection based on All Channels or ROI: All
Re-Referencing: On
 - Re-Reference Method: average
Visualizations: Off
Save Format: .txt file

The Pipeline QC contains NaN's and the data QC file contains values for file length in seconds, but "ERROR" in every other field. Lastly here is the errors log for each file:
Error Message: readlocs(): cannot find the named file or variable, check syntax
Stack Trace: Line 677 in ÇŠ; Line 729 in load_file_or_array; Line 114 in eadlocs; Line 112 in op_chanedit; Line 449 in HAPPE_v3

Thanks for your help on this! I am following the instructions in the HAPPE User Guide and the parameters from the Tutorial doc from the Zenodo page, but these messages from the command window might also be helpful:
EGI channel location automatically detected GSN129.sfp ********* WARNING please check that this the proper file
readlocs(): 'sfp' format assumed from file extension

**Comment by PINE-Lab** [comment]
Hi! We just pushed a bug fix that should hopefully address this issue! If not, please reach back out to us!
