### ISSUE TITLE
Using event label, rather than code, to distinguish events

### ISSUE THREAD

**Issue by jibrjabr** [PINE-Lab/HAPPE#5]
The code tag for my data is the same for all conditions ("Stim"), which I think creates an issue when using similarity for rejecting segments (if I include it, ~50 % of segments are rejected; with amplitude alone, ~10 % or less). Is there an easy way to use the event label tag instead of code so that the similarity measure will only apply within condition?

**Comment by PINE-Lab** [comment]
Segment rejection is performed across all segments irrespective of the event tag/code. If you're happy with the performance of using amplitude criteria alone, you're welcome to use that setting instead of using both amplitude and similarity criteria!

**Comment by jibrjabr** [comment]
Great, thanks for clarifying this!
