### ISSUE TITLE
Issues with HAPPE Preprocessing

### ISSUE THREAD

**Issue by ZahraMoradi1998** [PINE-Lab/HAPPE#7]
Dear HAPPE Support Team,

I am writing to seek guidance and assistance regarding my difficulties in working with the HAPPE preprocessing method.
I have thoroughly reviewed the HAPPE User Guide as well as the research paper titled "The Harvard Automated Processing Pipeline for Electroencephalography (HAPPE): Standardized Processing Software for Developmental and High-Artifact Data," but I still find myself confused and unsure about certain aspects.
To provide you with an overview of my data, I have 53 channels of EEG data collected during a muscular task. The sampling frequency of the data is 1200, and I have a total of 20 trials. Each trial consists of two sections: a rest section lasting for 10 seconds, followed by a task section lasting for 5 seconds. Consequently, my data spans a duration of 5 minutes, amounting to 360,000 data points.
My goal is to preprocess this data using the HAPPE method. I would like to inquire whether it is possible to obtain the preprocessed data for each trial, as well as for each section (task and rest), separately using segmentation. Is there a recommended approach for preprocessing the data in terms of considering each trial and section individually versus preprocessing all the data as a whole?

Furthermore, I would greatly appreciate any suggestions or recommendations you might have for the subsequent analysis of my preprocessed data. I have attempted to run HAPPE multiple times, employing different parameter settings, but unfortunately, I have not obtained the desired results.
Your expertise and guidance in resolving my confusion and addressing the issues I have encountered would be immensely valuable to me.

Thank you in advance for your time and support. I look forward to your response.

Best regards,
[Zahra Moradi]

**Comment by PINE-Lab** [comment]
Hi Zahra,

You could approach this in two ways:
1. Run your data through HAPPE without segmenting, then manually segment your pre-processed data.
2. Depending on how your data is tagged, you could enter the tags used for rest, task, and trial onsets and use a general segment length that would encompass all data point for your sections/trials (e.g., 0 to 15 seconds). This would output by section and by trials. You may decide to go back in and re-segment your data pre-processed data to the appropriate length for the section type (e.g., shortening the rest sections to 10 seconds).

Please feel free to reach out if you run into any issues!

**Comment by ZahraMoradi1998** [comment]
Thank you for your response and attention. 

I have followed your suggestion and manually segmented the data after preprocessing. However, I still need some guidance and assistance on a few questions. First, I want to know if I used the right tags for the data using the EEG lab. I tagged the data with trial, rest, and task tags, but should I have used only rest and task tags? Also, the rest part starts at the first sample of each trial, so the trial tags and rest tags are in the same sample, and at the same time. Is that correct or not? Second, I am confused about the relationship between the rest and task tags and the trial. Are they separate conditions or not? For example, if I had “happy_face” and “sad_face” tags, would they both belong to the “faces” condition? In my case, do the rest and task tags belong to the trial condition or not?  I am unsure about the format of entering the conditions and including onset tags. Is Trial Rest Task the correct answer or not?

I appreciate your help in clarifying these points.

**Comment by ZahraMoradi1998** [comment]
> Hi Zahra,
> 
> You could approach this in two ways:
> 
> 1. Run your data through HAPPE without segmenting, then manually segment your pre-processed data.
> 2. Depending on how your data is tagged, you could enter the tags used for rest, task, and trial onsets and use a general segment length that would encompass all data point for your sections/trials (e.g., 0 to 15 seconds). This would output by section and by trials. You may decide to go back in and re-segment your data pre-processed data to the appropriate length for the section type (e.g., shortening the rest sections to 10 seconds).
> 
> Please feel free to reach out if you run into any issues!

Thank you for your response and attention.

I have followed your suggestion and manually segmented the data after preprocessing. However, I still need some guidance and assistance on a few questions. First, I want to know if I used the right tags for the data using the EEG lab. I tagged the data with trial, rest, and task tags, but should I have used only rest and task tags? Also, the rest part starts at the first sample of each trial, so the trial tags and rest tags are in the same sample, and at the same time. Is that correct or not? Second, I am confused about the relationship between the rest and task tags and the trial. Are they separate conditions or not? For example, if I had “happy_face” and “sad_face” tags, would they both belong to the “faces” condition? In my case, do the rest and task tags belong to the trial condition or not? I am unsure about the format of entering the conditions and including onset tags. Is Trial Rest Task the correct answer or not?

I appreciate your help in clarifying these points.

**Comment by ZahraMoradi1998** [comment]
Thank you for your response and attention.

I have followed your suggestion and manually segmented the data after preprocessing. However, I still need some guidance and assistance on a few questions. First, I want to know if I used the right tags for the data using the EEG lab. I tagged the data with trial, rest, and task tags, but should I have used only rest and task tags? Also, the rest part starts at the first sample of each trial, so the trial tags and rest tags are in the same sample, and at the same time. Is that correct or not? Second, I am confused about the relationship between the rest and task tags and the trial. Are they separate conditions or not? For example, if I had “happy_face” and “sad_face” tags, would they both belong to the “faces” condition? In my case, do the rest and task tags belong to the trial condition or not? I am unsure about the format of entering the conditions and including onset tags. Is Trial Rest Task the correct answer or not?

I appreciate your help in clarifying these points.

**Comment by PINE-Lab** [comment]
Hi Zahra,

It seems your questions are beyond the scope of HAPPE itself. For information about tags, I strongly recommend the EEGLAB documentation, which should be more helpful in determining how to tag your data. I've included the link here for your convenience: https://eeglab.org/

If you run into any issues with HAPPE itself, please feel free to reach back out!
