### ISSUE TITLE
keptTrials error

### ISSUE THREAD

**Issue by neil-gallagher** [PINE-Lab/HAPPE#8]
I am getting an error at line 855 of HAPPE_v3.m that states 'The end operator must be used within an array index expression.' I believe this occurs because you attempt to access the keptTrials array even if it has never been created. I think this occurs any time that segment rejection is turned off, since line 839 gets skipped in that case. I am using the second commit from 5/25, but it doesn't seem like anything has fixed this in the most recent commit.

**Comment by PINE-Lab** [comment]
Thank you for alerting us to this issue! We just pushed a fix that should address this error!
